### ISSUE TITLE
Rename twig functions a use templates for html tags

### ISSUE THREAD

**Issue by hason** [knpuniversity/webpack-encore-bundle#1]
I think it's more consistent to rename twig functions to snake_case naming convention:
`getWebpackCssFiles` -> `webpack_css_files`
`getWebpackJsFiles` -> `webpack_js_files`

And instead of two additional functions `renderWebpack*Tags` I recommend using templates:
```twig
{% block javascripts %}
    {{ parent() }}
    {{ include('@WebpackEncore/script_tags.html.twig', { entry: 'entry1', prefix: 'build/' }) }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ include('@WebpackEncore/link_tags.html.twig', { entry: 'entry1', prefix: 'build/' }) }}
{% endblock %}
```

**Comment by weaverryan** [comment]
> I think it's more consistent to rename twig functions to snake_case naming convention:

Hmm, you're right about that!

> And instead of two additional functions renderWebpack*Tags I recommend using templates:

That's WAY more work, and the arguments (options in this case) are way less discoverable. But, we could actually create these templates, and have the `renderWebpack*Tags()` use them internally.

Thanks for the attention :)

**Comment by weaverryan** [comment]
I've just renamed to lower case functions. But, I'm going to keep the extra "render" functions - I like them :)

Thanks!
